name: 'Disable Anniversary pack'

on:
  schedule:
    # Run annually at 04:00 UTC on January 11th.
    #- cron: '0 4 11 1 *'
  workflow_dispatch:

jobs:
  disable-anniversary-pack:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Disable pack
        run: |
          node scripts/disable-marker-pack.mjs anniversary
          git config user.name 'Mathias Bynens'
          git config user.email 'mathias@qiwi.be'
          git commit data -m 'Disable Anniversary pack' -m 'This patch disables the Tibia Anniversary markers now that the event (which runs from January 7th until January 10th) has come to an end.'
          git push
