name: 'Enable Percht Island pack'

on:
  schedule:
    # The Winterlight Solstice event runs from December 22 to January
    # 10, followed by 7 days of rewards.
    # Run annually at 04:00 UTC on December 1st.
    # See enable-orcsoberfest*.yml which overrides this in February.
    - cron: '0 4 1 12 *'
  workflow_dispatch:

jobs:
  import-markers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Enable pack
        run: |
          scripts/enable-pack.sh percht
          git config user.name 'Mathias Bynens'
          git config user.email 'mathias@qiwi.be'
          git commit data -m 'Enable Percht Island maps' -m 'This patch replaces the Orcsoberfest Island maps (and their markers) with the Percht Island maps (and their markers) in preparation for the upcoming event.'
          git push
